/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ReviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const JobId = IDL.Nat;
export const UserId = IDL.Principal;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'comment' : IDL.Text,
  'reviewerPrincipal' : UserId,
  'rating' : IDL.Nat,
  'revieweePrincipal' : UserId,
});
export const UserRole = IDL.Variant({
  'laborer' : IDL.Null,
  'maid' : IDL.Null,
  'homeowner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'yearsExperience' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'averageRating' : IDL.Opt(IDL.Float64),
  'maidCategory' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'completedJobsCount' : IDL.Opt(IDL.Nat),
  'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
  'location' : IDL.Text,
});
export const WorkType = IDL.Variant({
  'other' : IDL.Null,
  'cook' : IDL.Null,
  'houseCleaner' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'general' : IDL.Null,
  'electrical' : IDL.Null,
  'babysitter' : IDL.Null,
  'maidServices' : IDL.Null,
  'childcare' : IDL.Null,
  'laundry' : IDL.Null,
  'carpentry' : IDL.Null,
  'masonry' : IDL.Null,
});
export const JobStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'workType' : WorkType,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'timelineDays' : IDL.Nat,
  'createdAt' : Timestamp,
  'assignedWorker' : IDL.Opt(UserId),
  'description' : IDL.Text,
  'requiredMaterials' : IDL.Opt(IDL.Text),
  'budget' : IDL.Nat,
  'posterPrincipal' : UserId,
  'location' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'senderPrincipal' : UserId,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'relatedJobId' : IDL.Opt(JobId),
  'messageText' : IDL.Text,
  'userPrincipal' : UserId,
});
export const PaymentId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PaymentType = IDL.Variant({
  'completion' : IDL.Null,
  'deposit' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'homeownerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'amountPaid' : IDL.Nat,
  'paymentType' : PaymentType,
  'stripeSessionId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignWorker' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'cancelJob' : IDL.Func([IDL.Nat], [], []),
  'completeJob' : IDL.Func([IDL.Nat], [], []),
  'confirmPayment' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createReview' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text],
      [Review],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [UserProfile],
      [],
    ),
  'filterJobs' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(WorkType), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Job)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getMessagesForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyPostedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getPaymentsForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCompletedJobs' : IDL.Nat,
          'totalWorkers' : IDL.Nat,
          'totalJobs' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReviewsForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getReviewsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listMaids' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listWorkers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'postJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        WorkType,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Vec(ExternalBlob),
      ],
      [Job],
      [],
    ),
  'recordPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentType, IDL.Text],
      [Payment],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ReviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const JobId = IDL.Nat;
  const UserId = IDL.Principal;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'jobId' : JobId,
    'comment' : IDL.Text,
    'reviewerPrincipal' : UserId,
    'rating' : IDL.Nat,
    'revieweePrincipal' : UserId,
  });
  const UserRole = IDL.Variant({
    'laborer' : IDL.Null,
    'maid' : IDL.Null,
    'homeowner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'yearsExperience' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'averageRating' : IDL.Opt(IDL.Float64),
    'maidCategory' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'completedJobsCount' : IDL.Opt(IDL.Nat),
    'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
    'location' : IDL.Text,
  });
  const WorkType = IDL.Variant({
    'other' : IDL.Null,
    'cook' : IDL.Null,
    'houseCleaner' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'general' : IDL.Null,
    'electrical' : IDL.Null,
    'babysitter' : IDL.Null,
    'maidServices' : IDL.Null,
    'childcare' : IDL.Null,
    'laundry' : IDL.Null,
    'carpentry' : IDL.Null,
    'masonry' : IDL.Null,
  });
  const JobStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'workType' : WorkType,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'timelineDays' : IDL.Nat,
    'createdAt' : Timestamp,
    'assignedWorker' : IDL.Opt(UserId),
    'description' : IDL.Text,
    'requiredMaterials' : IDL.Opt(IDL.Text),
    'budget' : IDL.Nat,
    'posterPrincipal' : UserId,
    'location' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'jobId' : JobId,
    'senderPrincipal' : UserId,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'relatedJobId' : IDL.Opt(JobId),
    'messageText' : IDL.Text,
    'userPrincipal' : UserId,
  });
  const PaymentId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PaymentType = IDL.Variant({
    'completion' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'homeownerPrincipal' : UserId,
    'createdAt' : Timestamp,
    'jobId' : JobId,
    'amountPaid' : IDL.Nat,
    'paymentType' : PaymentType,
    'stripeSessionId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignWorker' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'cancelJob' : IDL.Func([IDL.Nat], [], []),
    'completeJob' : IDL.Func([IDL.Nat], [], []),
    'confirmPayment' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createReview' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text],
        [Review],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [UserProfile],
        [],
      ),
    'filterJobs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(WorkType), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Job)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getMessagesForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyPostedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getPaymentsForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCompletedJobs' : IDL.Nat,
            'totalWorkers' : IDL.Nat,
            'totalJobs' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReviewsForJob' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getReviewsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listMaids' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listWorkers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'postJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          WorkType,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Vec(ExternalBlob),
        ],
        [Job],
        [],
      ),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentType, IDL.Text],
        [Payment],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };