/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : JobId,
  'status' : JobStatus,
  'workType' : WorkType,
  'title' : string,
  'imageUrls' : Array<ExternalBlob>,
  'timelineDays' : bigint,
  'createdAt' : Timestamp,
  'assignedWorker' : [] | [UserId],
  'description' : string,
  'requiredMaterials' : [] | [string],
  'budget' : bigint,
  'posterPrincipal' : UserId,
  'location' : string,
}
export type JobId = bigint;
export type JobStatus = { 'assigned' : null } |
  { 'cancelled' : null } |
  { 'open' : null } |
  { 'completed' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'senderPrincipal' : UserId,
}
export type MessageId = bigint;
export interface Notification {
  'id' : NotificationId,
  'createdAt' : Timestamp,
  'read' : boolean,
  'relatedJobId' : [] | [JobId],
  'messageText' : string,
  'userPrincipal' : UserId,
}
export type NotificationId = bigint;
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'homeownerPrincipal' : UserId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'amountPaid' : bigint,
  'paymentType' : PaymentType,
  'stripeSessionId' : string,
}
export type PaymentId = bigint;
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export type PaymentType = { 'completion' : null } |
  { 'deposit' : null };
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'jobId' : JobId,
  'comment' : string,
  'reviewerPrincipal' : UserId,
  'rating' : bigint,
  'revieweePrincipal' : UserId,
}
export type ReviewId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'yearsExperience' : [] | [bigint],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'averageRating' : [] | [number],
  'maidCategory' : [] | [string],
  'phone' : string,
  'completedJobsCount' : [] | [bigint],
  'skills' : [] | [Array<string>],
  'location' : string,
}
export type UserRole = { 'laborer' : null } |
  { 'maid' : null } |
  { 'homeowner' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkType = { 'other' : null } |
  { 'cook' : null } |
  { 'houseCleaner' : null } |
  { 'plumbing' : null } |
  { 'painting' : null } |
  { 'general' : null } |
  { 'electrical' : null } |
  { 'babysitter' : null } |
  { 'maidServices' : null } |
  { 'childcare' : null } |
  { 'laundry' : null } |
  { 'carpentry' : null } |
  { 'masonry' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignWorker' : ActorMethod<[bigint, Principal], undefined>,
  'cancelJob' : ActorMethod<[bigint], undefined>,
  'completeJob' : ActorMethod<[bigint], undefined>,
  'confirmPayment' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createReview' : ActorMethod<[Principal, bigint, bigint, string], Review>,
  'createUserProfile' : ActorMethod<
    [string, string, string, UserRole],
    UserProfile
  >,
  'filterJobs' : ActorMethod<
    [[] | [string], [] | [WorkType], [] | [bigint]],
    Array<Job>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getMessagesForJob' : ActorMethod<[bigint], Array<Message>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyPostedJobs' : ActorMethod<[], Array<Job>>,
  'getPaymentsForJob' : ActorMethod<[bigint], Array<Payment>>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'totalCompletedJobs' : bigint,
      'totalWorkers' : bigint,
      'totalJobs' : bigint,
    }
  >,
  'getReviewsForJob' : ActorMethod<[bigint], Array<Review>>,
  'getReviewsForUser' : ActorMethod<[Principal], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listMaids' : ActorMethod<[], Array<UserProfile>>,
  'listWorkers' : ActorMethod<[], Array<UserProfile>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'postJob' : ActorMethod<
    [
      string,
      string,
      WorkType,
      string,
      bigint,
      bigint,
      [] | [string],
      Array<ExternalBlob>,
    ],
    Job
  >,
  'recordPayment' : ActorMethod<[bigint, bigint, PaymentType, string], Payment>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], Message>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateUserProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];